package com.discover.app.billing.repository;
import com.discover.app.billing.domain.*; import org.springframework.data.domain.*; import org.springframework.data.jpa.repository.*; import org.springframework.data.repository.query.Param; import java.time.LocalDate; import java.util.*;
public interface InvoiceRepository extends JpaRepository<Invoice,Long> {
 @Query("select i from Invoice i join fetch i.studentEnrollment e join fetch e.student s join fetch e.grade g join fetch i.academicYear y where i.status=:status and i.academicYear.id=:yearId and (:term is null or lower(s.admissionNumber) like lower(concat('%',:term,'%')) or lower(s.phoneNumber) like lower(concat('%',:term,'%'))) order by i.generationDate desc, i.id desc") Page<Invoice> searchIssued(@Param("status") InvoiceStatus status,@Param("yearId") Long yearId,@Param("term") String term,Pageable pageable);
 @Query("select distinct i from Invoice i join fetch i.studentEnrollment e join fetch e.student s join fetch e.grade g join fetch i.academicYear y left join fetch i.items where i.id=:id") Optional<Invoice> findDetailedById(@Param("id") Long id);
 boolean existsByStudentEnrollmentIdAndAcademicYearIdAndStatusAndBillingMonthAndItems_Frequency(Long enrollmentId,Long yearId,InvoiceStatus status,LocalDate billingMonth,FeeFrequency frequency);
 @Query("select i from Invoice i join fetch i.studentEnrollment e join fetch e.student s join fetch e.grade g join fetch i.academicYear y left join fetch i.items where i.academicYear.id=:yearId and i.studentEnrollment.id=:enrollmentId and i.status=:status order by i.generationDate desc, i.id desc") List<Invoice> findForStudentYear(@Param("enrollmentId") Long enrollmentId,@Param("yearId") Long yearId,@Param("status") InvoiceStatus status);
 @Query("select count(i) from Invoice i where i.academicYear.id=:yearId and i.status=:status and i.studentEnrollment.id=:enrollmentId and i.billingMonth=:billingMonth") long countMonthlyPeriod(@Param("yearId") Long yearId,@Param("status") InvoiceStatus status,@Param("enrollmentId") Long enrollmentId,@Param("billingMonth") LocalDate billingMonth);
 @Query("select i from Invoice i join fetch i.items where i.id=:id") Optional<Invoice> findWithItems(@Param("id") Long id);
}
